# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [1]:

import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix


(True,
 array([[2.+0.j, 2.-1.j],
        [2.+1.j, 3.+0.j]]))


## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [ ]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [15]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v


ModuleNotFoundError: No module named 'numpy'


## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [ ]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.




In [6]:
import numpy as np
matrix = np.array([[3,complex(2,1)],[complex(2,-1),1]])
ishermitan = np.allclose(matrix,matrix.conj().T)
if ishermitan:
    eigva,eigvec = np.linalg.eig(matrix)
    print("Is a Hermitan Matrix")
    print("Eigenvalues: ")
    print(eigva)
else:
    print("Is not a Hermitan Matrix")
    

Is a Hermitan Matrix
Eigenvalues: 
[ 4.44948974-5.06745162e-17j -0.44948974+5.06745162e-17j]


## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.



In [3]:
import numpy as np
import math
matrix = np.array([[1,complex(0,1)],[complex(0,1),1]])
matrix *= 1/math.sqrt(2)
isunitary = np.allclose(np.dot(matrix,matrix.conj().T), np.eye(2))
if isunitary:
    print("Is an Unitary Matrix")
    print("Verify:")
    print("UU^t = \n")
    print(np.dot(matrix,matrix.conj().T))
    
else:
    print("Is not a Unitary Matrix")

Is an Unitary Matrix
Verify:
UU^t = 

[[1.+0.00000000e+00j 0.+2.23711432e-17j]
 [0.-2.23711432e-17j 1.+0.00000000e+00j]]


## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.




In [11]:
import numpy as np

v1 = np.array([[complex(1,1)],[complex(2,-1)]])
v2 = np.array([[complex(1,2)],[3]])
print("Tensor product:")
print(np.kron(v1,v2))

Tensor product:
[[-1.+3.j]
 [ 3.+3.j]
 [ 4.+3.j]
 [ 6.-3.j]]


## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.



In [4]:
import numpy as np

m1 = np.array([[0,1],[1,0]])
m2 = np.array([[complex(0,1),0],[0,complex(0,-1)]])
print("Tensor product:")
print(np.kron(m1,m2))

Tensor product:
[[0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]]


## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)


In [26]:
import numpy as np
import math

# Definición de las compuertas cuánticas
H = np.array([[1, 1], [1, -1]]) / math.sqrt(2)
X = np.array([[0, 1], [1, 0]])


# Estado inicial |0⟩
matrix = np.array([[1], [0]])


# Posición 1 (Estado inicial)
print("|Y0> = ")
print(matrix)

# Posición 2 (Hadamard)
matrix = H @ matrix
print("\n|Y1> = ")
print(matrix)

# Posición 3 (X)
matrix = X @ matrix
print("\n|Y2> = ")
print(matrix)

# Posición 4 (Hadamard)
matrix = H @ matrix
print("\n|Y3> = ")
print(matrix)



|Y0> = 
[[1]
 [0]]

|Y1> = 
[[0.70710678]
 [0.70710678]]

|Y2> = 
[[0.70710678]
 [0.70710678]]

|Y3> = 
[[1.00000000e+00]
 [2.23711432e-17]]


Al calcular el resultado del experimento propuesto podemos ver que obtenemos un vector muy parecido a |0> que tiene 1 en la primera posicion y un valor muy cercano a 0 en la segunda posicion. La razon por la que no obtuvimos 0 excato seguramente fue por las aproximaciones que debe hacer el computador para calcular numeros con tantos digitos. De cualquier manera el resultado es el esperado segun la teoria. 

Tambien recree el experimento en los computadores cuanticos de IBM y obtuve el siguiente resultado:

![EXP IBM 1](images/capturadepantalla.png)



## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)

In [28]:
import numpy as np
import math

# Definición de las compuertas cuánticas
H = np.array([[1, 1], [1, -1]]) / math.sqrt(2)
X = np.array([[0, 1], [1, 0]])
Uf = np.array([[0,1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]])
I = np.array([[1,0],[0,1]])

# Estado inicial |0> x |1>
matrix = np.kron(np.array([[1], [0]]),np.array([[0],[1]]))



# Posición 1 (Estado inicial)
print("|Y0> = ")
print(matrix)

# Posición 2 (Hadamard x2)
matrix = (np.kron(H,H)) @ matrix
print("\n|Y1> = ")
print(matrix)

# Posición 3 (Uf)
matrix = Uf @ matrix
print("\n|Y2> = ")
print(matrix)

# Posición 4 (Hadamard)
matrix = (np.kron(H,I)) @ matrix
print("\n|Y3> = ")
print(matrix)

|Y0> = 
[[0]
 [1]
 [0]
 [0]]

|Y1> = 
[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]

|Y2> = 
[[-0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]

|Y3> = 
[[ 0.        ]
 [ 0.        ]
 [-0.70710678]
 [ 0.70710678]]


Al calcular el resultado del experimento, podemos ver que nos da como resultado un vector unitario que se puede reescribir como:

$$
\begin{pmatrix}
0 \\
0 \\
-\frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}}
\end{pmatrix}
$$

o como:

$$
-\frac{1}{\sqrt{2}} |10\rangle + \frac{1}{\sqrt{2}} |11\rangle
$$

lo que quiere decir que la probabilidad del qubit que sale de |1> tiene el 100% de probabilidad de terminar en el estado 1 y el qubit |0> tiene 50% de probabilidad de terminar en el estado 0 y 50% de probabilidad de terminar en el estado 1.
